### ISSUE TITLE
After init from guide with some error

### ISSUE THREAD

**Issue by C1tas** [zulip/hubot-zulip#11]
After i init hubot & hubot-zulip
then export server config like 
```
export HUBOT_ZULIP_SITE="https://yourZulipDomain.zulipchat.com/api"
export HUBOT_ZULIP_BOT="hubot-bot@example.com"
export HUBOT_ZULIP_API_KEY="your_key"
```
then i start the bot get some error

![Imgur](https://i.imgur.com/XKEJRLx.png)

**Comment by timabbott** [comment]
Check /var/log/zulip/errors.log on your Zulip server; it looks like your server is serving a 500 error, and that's what you'll need to debug.

**Comment by C1tas** [comment]
Thanks for your answer

ok, i found the error caused by gitlab bot.

![Imgur](https://i.imgur.com/ybU8ws8.png)

but how it send to my hubot
